use super::Level;
use crate::snake::Direction;
use euclid::Point2D;

#[allow(clippy::too_many_lines)]
pub fn base_levels() -> Vec<Level> {
    vec![
        Level {
            target_points: Some(10),
            start_position: Some(Point2D::new(1, 1)),
            start_direction: Some(Direction::Right),
            obstacles: vec![
                Point2D::new(0, 0),
                Point2D::new(1, 0),
                Point2D::new(2, 0),
                Point2D::new(3, 0),
                Point2D::new(4, 0),
                Point2D::new(5, 0),
                Point2D::new(6, 0),
                Point2D::new(7, 0),
                Point2D::new(8, 0),
                Point2D::new(9, 0),
                Point2D::new(10, 0),
                Point2D::new(11, 0),
                Point2D::new(12, 0),
                Point2D::new(0, 1),
                Point2D::new(12, 1),
                Point2D::new(0, 2),
                Point2D::new(12, 2),
                Point2D::new(0, 3),
                Point2D::new(12, 3),
                Point2D::new(0, 4),
                Point2D::new(12, 4),
                Point2D::new(0, 5),
                Point2D::new(12, 5),
                Point2D::new(0, 6),
                Point2D::new(12, 6),
                Point2D::new(0, 7),
                Point2D::new(12, 7),
                Point2D::new(0, 8),
                Point2D::new(12, 8),
                Point2D::new(0, 9),
                Point2D::new(12, 9),
                Point2D::new(0, 10),
                Point2D::new(12, 10),
                Point2D::new(0, 11),
                Point2D::new(12, 11),
                Point2D::new(0, 12),
                Point2D::new(1, 12),
                Point2D::new(2, 12),
                Point2D::new(3, 12),
                Point2D::new(4, 12),
                Point2D::new(5, 12),
                Point2D::new(6, 12),
                Point2D::new(7, 12),
                Point2D::new(8, 12),
                Point2D::new(9, 12),
                Point2D::new(10, 12),
                Point2D::new(11, 12),
                Point2D::new(12, 12),
            ],
            updates_per_second: 8,
            height: 13,
            width: 13,
        },
        Level {
            target_points: Some(10),
            start_position: Some(Point2D::new(1, 1)),
            start_direction: Some(Direction::Right),
            obstacles: vec![
                Point2D::new(0, 0),
                Point2D::new(1, 0),
                Point2D::new(2, 0),
                Point2D::new(3, 0),
                Point2D::new(4, 0),
                Point2D::new(5, 0),
                Point2D::new(6, 0),
                Point2D::new(7, 0),
                Point2D::new(8, 0),
                Point2D::new(9, 0),
                Point2D::new(10, 0),
                Point2D::new(11, 0),
                Point2D::new(12, 0),
                Point2D::new(0, 1),
                Point2D::new(12, 1),
                Point2D::new(0, 2),
                Point2D::new(12, 2),
                Point2D::new(0, 3),
                Point2D::new(12, 3),
                Point2D::new(0, 4),
                Point2D::new(12, 4),
                Point2D::new(0, 5),
                Point2D::new(5, 5),
                Point2D::new(6, 5),
                Point2D::new(7, 5),
                Point2D::new(12, 5),
                Point2D::new(0, 6),
                Point2D::new(5, 6),
                Point2D::new(6, 6),
                Point2D::new(7, 6),
                Point2D::new(12, 6),
                Point2D::new(0, 7),
                Point2D::new(5, 7),
                Point2D::new(6, 7),
                Point2D::new(7, 7),
                Point2D::new(12, 7),
                Point2D::new(0, 8),
                Point2D::new(12, 8),
                Point2D::new(0, 9),
                Point2D::new(12, 9),
                Point2D::new(0, 10),
                Point2D::new(12, 10),
                Point2D::new(0, 11),
                Point2D::new(12, 11),
                Point2D::new(0, 12),
                Point2D::new(1, 12),
                Point2D::new(2, 12),
                Point2D::new(3, 12),
                Point2D::new(4, 12),
                Point2D::new(5, 12),
                Point2D::new(6, 12),
                Point2D::new(7, 12),
                Point2D::new(8, 12),
                Point2D::new(9, 12),
                Point2D::new(10, 12),
                Point2D::new(11, 12),
                Point2D::new(12, 12),
            ],
            updates_per_second: 8,
            height: 13,
            width: 13,
        },
        Level {
            target_points: Some(10),
            start_position: Some(Point2D::new(5, 4)),
            start_direction: Some(Direction::Right),
            obstacles: vec![
                Point2D::new(0, 0),
                Point2D::new(1, 0),
                Point2D::new(2, 0),
                Point2D::new(3, 0),
                Point2D::new(4, 0),
                Point2D::new(5, 0),
                Point2D::new(6, 0),
                Point2D::new(7, 0),
                Point2D::new(8, 0),
                Point2D::new(9, 0),
                Point2D::new(10, 0),
                Point2D::new(11, 0),
                Point2D::new(12, 0),
                Point2D::new(0, 1),
                Point2D::new(1, 1),
                Point2D::new(2, 1),
                Point2D::new(12, 1),
                Point2D::new(0, 2),
                Point2D::new(1, 2),
                Point2D::new(12, 2),
                Point2D::new(0, 3),
                Point2D::new(12, 3),
                Point2D::new(0, 4),
                Point2D::new(12, 4),
                Point2D::new(0, 5),
                Point2D::new(12, 5),
                Point2D::new(0, 6),
                Point2D::new(4, 6),
                Point2D::new(5, 6),
                Point2D::new(6, 6),
                Point2D::new(7, 6),
                Point2D::new(8, 6),
                Point2D::new(12, 6),
                Point2D::new(0, 7),
                Point2D::new(12, 7),
                Point2D::new(0, 8),
                Point2D::new(12, 8),
                Point2D::new(0, 9),
                Point2D::new(12, 9),
                Point2D::new(0, 10),
                Point2D::new(11, 10),
                Point2D::new(12, 10),
                Point2D::new(0, 11),
                Point2D::new(10, 11),
                Point2D::new(11, 11),
                Point2D::new(12, 11),
                Point2D::new(0, 12),
                Point2D::new(1, 12),
                Point2D::new(2, 12),
                Point2D::new(3, 12),
                Point2D::new(4, 12),
                Point2D::new(5, 12),
                Point2D::new(6, 12),
                Point2D::new(7, 12),
                Point2D::new(8, 12),
                Point2D::new(9, 12),
                Point2D::new(10, 12),
                Point2D::new(11, 12),
                Point2D::new(12, 12),
            ],
            updates_per_second: 8,
            height: 13,
            width: 13,
        },
        Level {
            target_points: Some(100),
            start_position: Some(Point2D::new(1, 1)),
            start_direction: Some(Direction::Right),
            obstacles: vec![
                Point2D::new(0, 0),
                Point2D::new(2, 0),
                Point2D::new(3, 0),
                Point2D::new(4, 0),
                Point2D::new(5, 0),
                Point2D::new(6, 0),
                Point2D::new(7, 0),
                Point2D::new(8, 0),
                Point2D::new(9, 0),
                Point2D::new(10, 0),
                Point2D::new(11, 0),
                Point2D::new(12, 0),
                Point2D::new(0, 1),
                Point2D::new(12, 1),
                Point2D::new(0, 2),
                Point2D::new(1, 2),
                Point2D::new(2, 2),
                Point2D::new(3, 2),
                Point2D::new(4, 2),
                Point2D::new(5, 2),
                Point2D::new(6, 2),
                Point2D::new(7, 2),
                Point2D::new(8, 2),
                Point2D::new(9, 2),
                Point2D::new(10, 2),
                Point2D::new(12, 2),
                Point2D::new(0, 3),
                Point2D::new(12, 3),
                Point2D::new(0, 4),
                Point2D::new(2, 4),
                Point2D::new(3, 4),
                Point2D::new(4, 4),
                Point2D::new(5, 4),
                Point2D::new(6, 4),
                Point2D::new(7, 4),
                Point2D::new(8, 4),
                Point2D::new(9, 4),
                Point2D::new(10, 4),
                Point2D::new(11, 4),
                Point2D::new(12, 4),
                Point2D::new(0, 5),
                Point2D::new(12, 5),
                Point2D::new(0, 6),
                Point2D::new(1, 6),
                Point2D::new(2, 6),
                Point2D::new(3, 6),
                Point2D::new(4, 6),
                Point2D::new(5, 6),
                Point2D::new(6, 6),
                Point2D::new(7, 6),
                Point2D::new(8, 6),
                Point2D::new(9, 6),
                Point2D::new(10, 6),
                Point2D::new(12, 6),
                Point2D::new(0, 7),
                Point2D::new(12, 7),
                Point2D::new(0, 8),
                Point2D::new(2, 8),
                Point2D::new(3, 8),
                Point2D::new(4, 8),
                Point2D::new(5, 8),
                Point2D::new(6, 8),
                Point2D::new(7, 8),
                Point2D::new(8, 8),
                Point2D::new(9, 8),
                Point2D::new(10, 8),
                Point2D::new(11, 8),
                Point2D::new(12, 8),
                Point2D::new(0, 9),
                Point2D::new(12, 9),
                Point2D::new(0, 10),
                Point2D::new(1, 10),
                Point2D::new(2, 10),
                Point2D::new(3, 10),
                Point2D::new(4, 10),
                Point2D::new(5, 10),
                Point2D::new(6, 10),
                Point2D::new(7, 10),
                Point2D::new(8, 10),
                Point2D::new(9, 10),
                Point2D::new(10, 10),
                Point2D::new(12, 10),
                Point2D::new(0, 11),
                Point2D::new(12, 11),
                Point2D::new(0, 12),
                Point2D::new(2, 12),
                Point2D::new(3, 12),
                Point2D::new(4, 12),
                Point2D::new(5, 12),
                Point2D::new(6, 12),
                Point2D::new(7, 12),
                Point2D::new(8, 12),
                Point2D::new(9, 12),
                Point2D::new(10, 12),
                Point2D::new(11, 12),
                Point2D::new(12, 12),
            ],
            updates_per_second: 8,
            height: 13,
            width: 13,
        },
    ]
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn check_base_levels() {
        for level in base_levels() {
            let x_max = level
                .obstacles
                .iter()
                .max_by_key(|obstacle| obstacle.x)
                .unwrap()
                .x;

            let x_min = level
                .obstacles
                .iter()
                .min_by_key(|obstacle| obstacle.x)
                .unwrap()
                .x;

            let y_max = level
                .obstacles
                .iter()
                .max_by_key(|obstacle| obstacle.y)
                .unwrap()
                .y;

            let y_min = level
                .obstacles
                .iter()
                .min_by_key(|obstacle| obstacle.y)
                .unwrap()
                .y;

            assert!(x_max < level.width);
            assert!(x_min >= 0);
            assert!(y_max < level.height);
            assert!(y_min >= 0);
        }
    }
}
