name: Test, Format, Lint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_fmt:
    name: Check Rust Format (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    needs: check_fmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test_and_coverage:
    name: Run Tests + Coverage
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install cargo-tarpaulin (coverage tool)
        run: cargo install cargo-tarpaulin
      - name: Run Tests with Coverage
        run: cargo tarpaulin --ignore-tests --out Lcov --output-dir target/tarpaulin
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: target/tarpaulin/lcov.info
